-- =====================================================
-- CUSTOMER SHOPPING BEHAVIOR ANALYSIS
-- PostgreSQL
-- =====================================================


-- Q0. View first 20 records

SELECT *
FROM customer
LIMIT 20;


-- =====================================================
-- Q1. What is the total revenue generated by
-- male vs. female customers?
-- =====================================================

SELECT
    "Gender",
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Gender"
ORDER BY total_revenue DESC;


-- =====================================================
-- Q2. Which customers used a discount but still spent
-- more than the average purchase amount?
-- =====================================================

SELECT
    "Customer ID",
    "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes'
  AND "Purchase Amount (USD)" > (
      SELECT AVG("Purchase Amount (USD)")
      FROM customer
  )
ORDER BY "Purchase Amount (USD)" DESC;


-- =====================================================
-- Q3. Which are the top 5 products with the highest
-- average review rating?
-- =====================================================

SELECT
    "Item Purchased",
    ROUND(AVG("Review Rating"::NUMERIC), 2) AS average_product_rating
FROM customer
GROUP BY "Item Purchased"
ORDER BY average_product_rating DESC
LIMIT 5;


-- =====================================================
-- Q4. Compare the average Purchase Amounts between
-- Standard and Express Shipping.
-- =====================================================

SELECT
    "Shipping Type",
    ROUND(AVG("Purchase Amount (USD)"), 2) AS average_purchase_amount
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type"
ORDER BY average_purchase_amount DESC;


-- =====================================================
-- Q5. Do subscribed customers spend more?
-- Compare average spend and total revenue between
-- subscribers and non-subscribers.
-- =====================================================

SELECT
    "Subscription Status",
    COUNT("Customer ID") AS total_customers,
    ROUND(AVG("Purchase Amount (USD)"), 2) AS average_spend,
    ROUND(SUM("Purchase Amount (USD)"), 2) AS total_revenue
FROM customer
GROUP BY "Subscription Status"
ORDER BY total_revenue DESC;


-- =====================================================
-- Q6. Which 5 products have the highest percentage
-- of purchases with discounts applied?
-- =====================================================

SELECT
    "Item Purchased",
    ROUND(
        100.0 * SUM(
            CASE
                WHEN "Discount Applied" = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_rate_percentage
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_rate_percentage DESC
LIMIT 5;


-- =====================================================
-- Q7. Segment customers into New, Returning, and Loyal
-- based on their previous purchases.
-- =====================================================

WITH customer_type AS (
    SELECT
        "Customer ID",
        "Previous Purchases",
        CASE
            WHEN "Previous Purchases" <= 1 THEN 'New'
            WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY
    CASE customer_segment
        WHEN 'New' THEN 1
        WHEN 'Returning' THEN 2
        WHEN 'Loyal' THEN 3
    END;


-- =====================================================
-- Q8. What are the top 3 most purchased products
-- within each category?
-- =====================================================

WITH item_counts AS (
    SELECT
        "Category",
        "Item Purchased",
        COUNT(*) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY "Category"
            ORDER BY COUNT(*) DESC
        ) AS item_rank
    FROM customer
    GROUP BY
        "Category",
        "Item Purchased"
)

SELECT
    "Category",
    "Item Purchased",
    total_orders,
    item_rank
FROM item_counts
WHERE item_rank <= 3
ORDER BY
    "Category",
    item_rank;


-- =====================================================
-- Q9. Are customers who are repeat buyers
-- (more than 5 previous purchases) also likely to subscribe?
-- =====================================================

SELECT
    "Subscription Status",
    COUNT(*) AS repeat_buyers
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status"
ORDER BY repeat_buyers DESC;


-- =====================================================
-- Q10. What is the revenue contribution of each age group?
-- =====================================================

-- Q10. What is the revenue contribution of each age group?

SELECT
    CASE
        WHEN "Age" BETWEEN 18 AND 25 THEN '18-25'
        WHEN "Age" BETWEEN 26 AND 35 THEN '26-35'
        WHEN "Age" BETWEEN 36 AND 45 THEN '36-45'
        WHEN "Age" BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
    END AS age_group,
    
    SUM("Purchase Amount (USD)") AS total_revenue

FROM customer

GROUP BY
    CASE
        WHEN "Age" BETWEEN 18 AND 25 THEN '18-25'
        WHEN "Age" BETWEEN 26 AND 35 THEN '26-35'
        WHEN "Age" BETWEEN 36 AND 45 THEN '36-45'
        WHEN "Age" BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
    END

ORDER BY total_revenue DESC;